# Classification

- Target = 0 if suicide rate <= national median
- Target = 1 if suicide rate > national median
- Features  = disease rates + state

Import libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.feature_selection import RFE,SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from skopt import gp_minimize
import time
import glob
root = "../../"

In [2]:
dict_uf_cod = {11: 'RO',
12: 'AC',
13: 'AM',
14: 'RR',
15: 'PA',
16: 'AP',
17: 'TO',
21: 'MA',
22: 'PI',
23: 'CE',
24: 'RN',
25: 'PB',
26: 'PE',
27: 'AL',
28: 'SE',
29: 'BA',
31: 'MG',
32: 'ES',
33: 'RJ',
35: 'SP',
41: 'PR',
42: 'SC',
43: 'RS',
50: 'MS',
51: 'MT',
52: 'GO',
53: 'DF'}

Prepare dataset

In [3]:
disease = ""
path = root + "CSV/TabNet/Internacoes_Rate/"
all_files = glob.glob(path + "*.csv")
suicide = pd.read_csv(root +'CSV/Suicide/suicide_rates_08_18.csv', index_col=0)

years = [str(x).zfill(2) for x in range(8,19)]
columns = ["RATE_" + year for year in years]
columns.append("MUNCOD")

disease_list = []

for file in all_files:
    file_name = file.split("\\")[-1]
    disease = file_name.split(".csv")[0]
    disease_df = pd.read_csv(file, sep=',', index_col=0)
    if(set(disease_df.columns) == set(columns)):
        disease_list.append(disease)
print(len(disease_list), " diseases")

313  diseases


In [4]:
initial_df = pd.DataFrame()
percentage_valid_values = 0.8
for i in range(0,len(years)-1):
    col_year_suicide = "RATE_" + years[i+1]
    year_df = suicide[[col_year_suicide, "MUNCOD"]].copy()
    
    for disease in disease_list:
        col_year_disease = "RATE_" + years[i]
        disease_df = pd.read_csv(path + disease + ".csv", sep=',', index_col=0)
        disease_df = disease_df[[col_year_disease, "MUNCOD"]]
        disease_df[disease] = disease_df[col_year_disease] 
        disease_df = disease_df.drop(columns={col_year_disease})
        year_df = pd.merge(disease_df, year_df, left_on="MUNCOD", right_on="MUNCOD", how='right')
    N = int(year_df.shape[1]*percentage_valid_values)
    year_df = year_df.dropna(thresh=N) # a column needs at least N non-NaNs to survive
    year_df["TARGET"] = (year_df[col_year_suicide] > year_df[col_year_suicide].median()).astype(int)
    year_df = year_df.drop(columns=col_year_suicide)
    initial_df = pd.concat([initial_df, year_df])

initial_df.head()

MUNCOD  ÚLCERA_GÁSTRICA_E_DUODENAL  \
0  110001                   28.481914   
1  110002                    9.458389   
3  110004                    5.110972   
8  110009                    0.000000   
9  110010                    2.466639   

   VEIAS_VARICOSAS_DAS_EXTREMIDADES_INFERIORES  VARICELA_E_HERPES_ZOSTER  \
0                                    40.688449                       0.0   
1                                    54.385737                       0.0   
3                                    21.721631                       0.0   
8                                    48.921969                       0.0   
9                                     9.866555                       0.0   

   UROLITÍASE  TÉTANO_NEONATAL  TUBERC_INTEST_PERITÔNIO_GLÂNGL_MESENTÉRICOS  \
0  142.409570              NaN                                          NaN   
1   15.369882              NaN                                          0.0   
3   63.887150              NaN                                          NaN   
8   24.460985              NaN                                          NaN   
9   12.333194              NaN                                          0.0   

   TUBERCULOSE_ÓSSEA_E_DAS_ARTICULAÇÕES  TUBERCULOSE_PULMONAR  \
0                                   NaN                   0.0   
1                                   NaN                   0.0   
3                                   NaN                   0.0   
8                                   NaN                   0.0   
9                                   0.0                   0.0   

   TUBERCULOSE_MILIAR  ...  ANEMIA_POR_DEFICIÊNCIA_DE_FERRO  ANCILOSTOMÍASE  \
0                 NaN  ...                         0.000000             NaN   
1                 0.0  ...                         0.000000             NaN   
3                 0.0  ...                         2.555486             NaN   
8                 NaN  ...                         0.000000             NaN   
9                 0.0  ...                        41.932858             0.0   

   AMEBÍASE  ALGUNS_TRANSTORNOS_ENVOLVENDO_MECANISMO_IMUNITÁRIO  \
0  0.000000                                                NaN    
1  0.000000                                                0.0    
3       NaN                                                0.0    
8  0.000000                                                NaN    
9  2.466639                                                NaN    

   AFECÇ_HEMORRÁG_E_OUTR_DOENÇ_SANG_E_ÓRG_HEMATOPOÉT  \
0                                          44.757293   
1                                           1.182299   
3                                           3.833229   
8                                           3.494426   
9                                           2.466639   

   ACID_VASCULAR_CEREBR_NÃO_ESPEC_HEMORRÁG_OU_ISQUÊM  \
0                                          40.688449   
1                                          39.015855   
3                                         106.052669   
8                                           0.000000   
9                                          36.999581   

   ACID_VASCULAR_CEREBR_ISQUÊM_TRANSIT_E_SÍNDR_CORREL  \
0                                          32.550759    
1                                           0.000000    
3                                           3.833229    
8                                          17.472132    
9                                           0.000000    

   ABORTO_POR_RAZÕES_MÉDICAS  ABORTO_ESPONTÂNEO  TARGET  
0                        NaN         126.134191       1  
1                        0.0           1.182299       0  
3                        0.0           2.555486       1  
8                        0.0           0.000000       1  
9                        0.0         197.331097       1  

[5 rows x 315 columns]

In [5]:
df = initial_df.copy()
df = df.fillna(0)

Checking the number of 0s and 1s in TARGET column

In [6]:
unique, counts = np.unique(df["TARGET"].values, return_counts=True)
dict(zip(unique, counts))

{0: 4680, 1: 4670}

Get UF from MUNCOD

In [7]:
df['UF'] = df['MUNCOD'] / 10000
df['UF'] = df['UF'].astype(int)
df['UF'].replace(dict_uf_cod, inplace=True)
dummy = pd.get_dummies(df['UF'])
df = pd.concat([df, dummy], axis=1)
df = df.drop(['MUNCOD', 'UF'], axis=1)
df.head()

ÚLCERA_GÁSTRICA_E_DUODENAL  VEIAS_VARICOSAS_DAS_EXTREMIDADES_INFERIORES  \
0                   28.481914                                    40.688449   
1                    9.458389                                    54.385737   
3                    5.110972                                    21.721631   
8                    0.000000                                    48.921969   
9                    2.466639                                     9.866555   

   VARICELA_E_HERPES_ZOSTER  UROLITÍASE  TÉTANO_NEONATAL  \
0                       0.0  142.409570              0.0   
1                       0.0   15.369882              0.0   
3                       0.0   63.887150              0.0   
8                       0.0   24.460985              0.0   
9                       0.0   12.333194              0.0   

   TUBERC_INTEST_PERITÔNIO_GLÂNGL_MESENTÉRICOS  \
0                                          0.0   
1                                          0.0   
3                                          0.0   
8                                          0.0   
9                                          0.0   

   TUBERCULOSE_ÓSSEA_E_DAS_ARTICULAÇÕES  TUBERCULOSE_PULMONAR  \
0                                   0.0                   0.0   
1                                   0.0                   0.0   
3                                   0.0                   0.0   
8                                   0.0                   0.0   
9                                   0.0                   0.0   

   TUBERCULOSE_MILIAR  TUBERCULOSE_DO_SISTEMA_NERVOSO  ...  PR  RJ  RN  RO  \
0                 0.0                             0.0  ...   0   0   0   1   
1                 0.0                             0.0  ...   0   0   0   1   
3                 0.0                             0.0  ...   0   0   0   1   
8                 0.0                             0.0  ...   0   0   0   1   
9                 0.0                             0.0  ...   0   0   0   1   

   RR  RS  SC  SE  SP  TO  
0   0   0   0   0   0   0  
1   0   0   0   0   0   0  
3   0   0   0   0   0   0  
8   0   0   0   0   0   0  
9   0   0   0   0   0   0  

[5 rows x 341 columns]

Define X and y

In [8]:
X = df.drop(columns=["TARGET"])
y = df["TARGET"]

X.shape

(9350, 340)

Define some functions

In [9]:
def get_average_feat_importance(feature_importance_list):
    final_feat_df = pd.DataFrame()
    for i, feat_df in enumerate(feature_importance_list):
        feat_df = feat_df.rename(columns={"Importance": i})
        if final_feat_df.empty:
            final_feat_df = feat_df
        else:
            final_feat_df = pd.merge(final_feat_df, feat_df, on="Feature", how="right")
    final_feat_df = final_feat_df.fillna(0)
    final_feat_df["Avg_importance"] = final_feat_df.sum(axis=1)/(final_feat_df.shape[1] -1)
    final_feat_df = final_feat_df[["Feature", "Avg_importance"]]
    return final_feat_df.sort_values(by="Avg_importance", ascending=False)

In [10]:
def sfm_feature_selector(X_train,y_train,max_features):
    embeded_rf_selector = SelectFromModel(RandomForestClassifier(n_estimators=100),max_features=max_features)
    embeded_rf_selector.fit(X_train, y_train)

    embeded_rf_support = embeded_rf_selector.get_support()
    embeded_rf_feature = X_train.loc[:,embeded_rf_support].columns.tolist()
    print(str(len(embeded_rf_feature)), 'selected features (SFM)')
    return embeded_rf_feature

In [11]:
def get_average(scores_list):
    scores_avg_test = []
    for i in range(len(scores_list[0])):
        arr_list = [x[i] for x in scores_list]
        avg_result = np.array(arr_list).mean(axis=0)
        scores_avg_test.append(avg_result)
    return scores_avg_test

First model

In [15]:
from sklearn.model_selection import StratifiedKFold
start = time.time()
num_feat = 30
kf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 42)
scores = pd.DataFrame({"accuracy_train": [], "accuracy_test": [], "scores_train": [], "scores_test": []})
feature_importance_list = []
count = 1
for train_index, test_index in kf.split(X,y):
    print("=============== RUN {} ===============".format(count))
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    print("# Feature Selection: SFM")
    selected_sfm_features = sfm_feature_selector(X_train,y_train,num_feat)
    X_train = X_train[selected_sfm_features]
    X_test = X_test[selected_sfm_features]
    
    print("# Bayesian Optimization")
    def train_model(params):
        n_estimators = params[0]
        max_depth = params[1]
        min_samples_leaf = params[2]
        max_features = params[3]

        xf_train_params,xf_val,yf_train_params,yf_val = train_test_split(X_train,y_train,test_size=0.33,random_state=42)

        model = RandomForestClassifier(n_jobs=-1, random_state=42,n_estimators=n_estimators, 
                                      max_depth=max_depth,min_samples_leaf=min_samples_leaf,max_features=max_features)

        model.fit(xf_train_params,yf_train_params)
        yf_pred = model.predict(xf_val)

        return metrics.accuracy_score(yf_val, yf_pred)
    space = [
        (5,1000), #n_estimators
        (3,30), #max_depth
        (2,200), #min_samples_leaf
        (0.25,1.00) #max_features
    ]
    resultado_gp = gp_minimize(train_model, space, random_state=42, verbose=0, n_calls=30, n_random_starts=10)
    
    n_estimators = resultado_gp.x[0]
    max_depth = resultado_gp.x[1]
    min_samples_leaf = resultado_gp.x[2]
    max_features = resultado_gp.x[3]
    
    print("# Fitting the model")
    classifier = RandomForestClassifier(random_state=42,n_estimators=n_estimators, 
                                      max_depth=max_depth,min_samples_leaf=min_samples_leaf,max_features=max_features)
    classifier.fit(X_train,y_train)
    
    print("# Making predictions")
    y_pred = classifier.predict(X_test) 
    y_pred_train = classifier.predict(X_train)
    
    print("# Calculating metrics")
    print("Train")
    print(metrics.confusion_matrix(y_train, y_pred_train))
    print(metrics.classification_report(y_train, y_pred_train, digits=3))
    print("Test")
    print(metrics.confusion_matrix(y_test, y_pred))
    print(metrics.classification_report(y_test, y_pred, digits=3))
    scores = scores.append({"accuracy_train": metrics.accuracy_score(y_train,y_pred_train),
                  "accuracy_test": metrics.accuracy_score(y_test,y_pred),
                  "scores_train": metrics.precision_recall_fscore_support(y_train,y_pred_train),
                  "scores_test": metrics.precision_recall_fscore_support(y_test,y_pred)}, ignore_index=True)
    
    print("# Get Feature Importance")
    importance = classifier.feature_importances_
    feature_importance_list.append(pd.DataFrame({"Feature": X_train.columns, "Importance": importance}).sort_values(by="Importance", ascending=False))
    
    print("\n")
    count += 1
print("=============== SUMMARY ===============")
print("# Average Feature Importance")
final_feat_df = get_average_feat_importance(feature_importance_list)
print(final_feat_df.head(20))

print("# Average Metrics")
print("## Train")
avg_accuracy_train = scores["accuracy_train"].mean()
avg_score_train = get_average(scores["scores_train"])
print("accuracy_train:", avg_accuracy_train)
print("precision_train:", avg_score_train[0].mean())
print("recall_train:", avg_score_train[1].mean())
print("f1_score_train:", avg_score_train[2].mean())
print("## Test")
avg_accuracy_test = scores["accuracy_test"].mean()
avg_score_test = get_average(scores["scores_test"])
print("accuracy_test:", avg_accuracy_test)
print("precision_test:", avg_score_test[0].mean())
print("recall_test:", avg_score_test[1].mean())
print("f1_score_test:", avg_score_test[2].mean())

end = time.time()

print("\nTotal run time:", end-start)

=============== RUN 1 ===============
# Feature Selection: SFM
30 selected features (SFM)
# Bayesian Optimization


C:\Users\pypas\anaconda3\envs\ML\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


# Fitting the model
# Making predictions
# Calculating metrics
Train
[[2405 1339]
 [1264 2472]]
              precision    recall  f1-score   support

           0      0.655     0.642     0.649      3744
           1      0.649     0.662     0.655      3736

    accuracy                          0.652      7480
   macro avg      0.652     0.652     0.652      7480
weighted avg      0.652     0.652     0.652      7480

Test
[[597 339]
 [347 587]]
              precision    recall  f1-score   support

           0      0.632     0.638     0.635       936
           1      0.634     0.628     0.631       934

    accuracy                          0.633      1870
   macro avg      0.633     0.633     0.633      1870
weighted avg      0.633     0.633     0.633      1870

# Get Feature Importance


=============== RUN 2 ===============
# Feature Selection: SFM
30 selected features (SFM)
# Bayesian Optimization


C:\Users\pypas\anaconda3\envs\ML\lib\site-packages\skopt\optimizer\optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "


# Fitting the model
# Making predictions
# Calculating metrics
Train
[[2570 1174]
 [1462 2274]]
              precision    recall  f1-score   support

           0      0.637     0.686     0.661      3744
           1      0.660     0.609     0.633      3736

    accuracy                          0.648      7480
   macro avg      0.648     0.648     0.647      7480
weighted avg      0.648     0.648     0.647      7480

Test
[[616 320]
 [359 575]]
              precision    recall  f1-score   support

           0      0.632     0.658     0.645       936
           1      0.642     0.616     0.629       934

    accuracy                          0.637      1870
   macro avg      0.637     0.637     0.637      1870
weighted avg      0.637     0.637     0.637      1870

# Get Feature Importance


=============== RUN 3 ===============
# Feature Selection: SFM
30 selected features (SFM)
# Bayesian Optimization
# Fitting the model
# Making predictions
# Calculating metrics
Train
[[2558 1186]